name             'rails-stack'
maintainer       'JetThoughts'
maintainer_email 'michael@jetthoughts.com'
license          'All rights reserved'
description      'Installs/Configures rails-stack'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.10'

depends          'rbenv'
depends          'nginx'
depends          'postgresql'
depends          'delayed_job'
depends          'rails_stack_sidekiq_monit'
depends          'unicorn'
depends          'sudo'
depends          'nodejs'
depends          'postfix'
depends          'imagemagick'
depends          'memcached'
depends          'logrotate'
depends          'monit'
depends          'yum-epel'
depends          'mysql2_chef_gem'
depends          'database', '~> 4.0.3'
depends          'mysql', '~> 6.0'
depends          'redis'
